#!/usr/bin/env bash
set -euo pipefail

GHOSTFORGE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GREEN='\033[0;32m'; BLUE='\033[0;34m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BOLD='\033[1m'; DIM='\033[2m'; NC='\033[0m'

SPEC_URL=""
OUT_FILE="src/types/api.generated.ts"
GEN_SERVICE=false
CLIENT="fetch"

# Parse args
for arg in "$@"; do
  case "$arg" in
    --service) GEN_SERVICE=true ;;
    --client=*) CLIENT="${arg#--client=}" ;;
    --out=*) OUT_FILE="${arg#--out=}" ;;
    http*|./*|/*) SPEC_URL="$arg" ;;
  esac
done

echo ""
echo -e "${BLUE}${BOLD}  ╔═════════════════════════════════════════╗${NC}"
echo -e "${BLUE}${BOLD}  ║   /api-types — OpenAPI → TypeScript     ║${NC}"
echo -e "${BLUE}${BOLD}  ╚═════════════════════════════════════════╝${NC}"
echo ""

# Prompt for URL if not provided
if [[ -z "$SPEC_URL" ]]; then
  echo -e "  ${DIM}Enter your OpenAPI/Swagger spec URL or local file path:${NC}"
  read -rp "  > " SPEC_URL
fi

if [[ -z "$SPEC_URL" ]]; then
  echo -e "  ${RED}✖  No spec URL provided. Exiting.${NC}"
  exit 1
fi

echo -e "  ${BLUE}Spec:${NC} $SPEC_URL"
echo -e "  ${BLUE}Output:${NC} $OUT_FILE"
echo ""

# Create output directory
mkdir -p "$(dirname "$OUT_FILE")"

# Run openapi-typescript
echo -e "  ${DIM}Running openapi-typescript...${NC}"
if npx --yes openapi-typescript@latest "$SPEC_URL" --output "$OUT_FILE" 2>&1; then
  TYPE_COUNT=$(grep -c "^export" "$OUT_FILE" 2>/dev/null || echo "?")
  echo ""
  echo -e "  ${GREEN}✅ Types generated:${NC} ${BOLD}$OUT_FILE${NC}"
  echo -e "  ${DIM}   Exported types: ~$TYPE_COUNT${NC}"
else
  echo -e "  ${RED}✖  openapi-typescript failed.${NC}"
  echo -e "  ${DIM}  Tip: Make sure the URL is accessible and returns valid OpenAPI JSON/YAML${NC}"
  exit 1
fi

# Generate service file if requested
if $GEN_SERVICE; then
  SERVICE_FILE="src/services/api.service.ts"
  mkdir -p "$(dirname "$SERVICE_FILE")"
  echo ""
  echo -e "  ${BLUE}Generating API service file...${NC}"

  cat > "$SERVICE_FILE" << 'SERVICEOF'
/**
 * Auto-generated API service
 * Generated by GhostForge /api-types
 * Do not edit manually — regenerate with: bash scripts/api-types.sh --service
 */

const API_BASE = process.env.NEXT_PUBLIC_API_URL || process.env.REACT_APP_API_URL || '';

async function apiFetch<T>(path: string, options?: RequestInit): Promise<T> {
  const res = await fetch(`${API_BASE}${path}`, {
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...(options?.headers ?? {}),
    },
  });
  if (!res.ok) {
    const error = await res.text().catch(() => res.statusText);
    throw new Error(`API Error ${res.status}: ${error}`);
  }
  return res.json() as Promise<T>;
}

export const apiGet = <T>(path: string) => apiFetch<T>(path);
export const apiPost = <T>(path: string, body: unknown) =>
  apiFetch<T>(path, { method: 'POST', body: JSON.stringify(body) });
export const apiPut = <T>(path: string, body: unknown) =>
  apiFetch<T>(path, { method: 'PUT', body: JSON.stringify(body) });
export const apiPatch = <T>(path: string, body: unknown) =>
  apiFetch<T>(path, { method: 'PATCH', body: JSON.stringify(body) });
export const apiDelete = <T>(path: string) =>
  apiFetch<T>(path, { method: 'DELETE' });
SERVICEOF

  echo -e "  ${GREEN}✅ Service file generated:${NC} ${BOLD}$SERVICE_FILE${NC}"
fi

# Format with prettier if available
if command -v npx &>/dev/null && npx --no-install prettier --version &>/dev/null 2>&1; then
  echo ""
  echo -e "  ${DIM}Formatting with Prettier...${NC}"
  npx --no-install prettier --write "$OUT_FILE" ${GEN_SERVICE:+"$SERVICE_FILE"} 2>/dev/null || true
  echo -e "  ${GREEN}✔${NC} Formatted"
fi

echo ""
echo -e "  ${GREEN}${BOLD}✅ Done!${NC}"
echo -e "  ${DIM}Import types: import type { YourType } from '@/types/api.generated'${NC}"
echo ""
