#!/usr/bin/env bash
set -euo pipefail
RED='\033[0;31m' GREEN='\033[0;32m' YELLOW='\033[1;33m' CYAN='\033[0;36m' NC='\033[0m' BOLD='\033[1m' DIM='\033[2m'

ACTION="${1:-help}"
shift || true
DATA_DIR="$HOME/.ghostforge/graphql"
PROJECT_SLUG="$(basename "$(pwd)" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-')"
ENDPOINT_FILE=".ghostforge-graphql-endpoint"
SCHEMA_DIR="src/graphql"
SCHEMA_JSON="$SCHEMA_DIR/schema.json"
SCHEMA_GRAPHQL="$SCHEMA_DIR/schema.graphql"
TYPES_FILE="$SCHEMA_DIR/types.ts"
CACHE_REMOTE=".ghostforge-graphql-remote.json"
mkdir -p "$DATA_DIR" "$SCHEMA_DIR"

header() {
  echo ""
  echo -e "${CYAN}${BOLD}  🔷  GhostForge GraphQL Type Sync${NC}"
  echo -e "${DIM}  Introspect GraphQL APIs and generate schema + TypeScript types.${NC}"
  echo ""
}

persist_endpoint() {
  printf '%s\n' "$1" > "$ENDPOINT_FILE"
  printf '%s\n' "$1" > "$DATA_DIR/${PROJECT_SLUG}.endpoint"
}

read_endpoint() {
  if [[ -f "$ENDPOINT_FILE" ]]; then
    cat "$ENDPOINT_FILE"
  elif [[ -f "$DATA_DIR/${PROJECT_SLUG}.endpoint" ]]; then
    cat "$DATA_DIR/${PROJECT_SLUG}.endpoint"
  fi
}

fetch_schema() {
  local endpoint="$1" target="$2"
  python3 - <<'PY' "$endpoint" "$target"
import json, sys, urllib.request

endpoint, target = sys.argv[1:3]
query = """query IntrospectionQuery { __schema { queryType { name } mutationType { name } subscriptionType { name } types { kind name description fields(includeDeprecated: true) { name description args { name description type { kind name ofType { kind name ofType { kind name ofType { kind name } } } } defaultValue } type { kind name ofType { kind name ofType { kind name ofType { kind name } } } } isDeprecated deprecationReason } inputFields { name description type { kind name ofType { kind name ofType { kind name ofType { kind name } } } } defaultValue } interfaces { kind name ofType { kind name } } enumValues(includeDeprecated: true) { name description isDeprecated deprecationReason } possibleTypes { kind name ofType { kind name } } } directives { name description locations args { name description type { kind name ofType { kind name ofType { kind name } } } defaultValue } } } }"""
req = urllib.request.Request(endpoint, data=json.dumps({"query": query}).encode("utf-8"), headers={"Content-Type": "application/json"})
with urllib.request.urlopen(req) as response:
    data = json.loads(response.read().decode("utf-8"))
if "errors" in data:
    raise SystemExit(json.dumps(data["errors"]))
with open(target, "w", encoding="utf-8") as fh:
    json.dump(data, fh, indent=2)
print(target)
PY
}

generate_from_introspection() {
  node - <<'NODE' "$SCHEMA_JSON" "$SCHEMA_GRAPHQL" "$TYPES_FILE"
const fs = require('fs');
const [jsonFile, sdlFile, typesFile] = process.argv.slice(2);
const data = JSON.parse(fs.readFileSync(jsonFile, 'utf8')).data.__schema;
const builtins = new Set(['String', 'Int', 'Float', 'Boolean', 'ID']);
const scalarMap = { String: 'string', ID: 'string', Int: 'number', Float: 'number', Boolean: 'boolean' };
const visibleTypes = data.types.filter(t => t.name && !t.name.startsWith('__'));

function unwrap(type) {
  if (!type) return { sdl: 'String', ts: 'string', required: false };
  if (type.kind === 'NON_NULL') {
    const inner = unwrap(type.ofType);
    return { ...inner, sdl: `${inner.sdl}!`, required: true };
  }
  if (type.kind === 'LIST') {
    const inner = unwrap(type.ofType);
    return { sdl: `[${inner.sdl}]`, ts: `Array<${inner.ts}>`, required: false };
  }
  const name = type.name || 'String';
  return { sdl: name, ts: scalarMap[name] || name, required: false };
}

const sdl = [];
const ts = [
  '/* eslint-disable */',
  '// Auto-generated by GhostForge GraphQL Sync',
  '',
  'export type Maybe<T> = T | null;',
  ''
];

for (const type of visibleTypes) {
  if (type.kind === 'SCALAR' && !builtins.has(type.name)) {
    sdl.push(`scalar ${type.name}`);
    ts.push(`export type ${type.name} = string;`, '');
  }
  if (type.kind === 'ENUM') {
    sdl.push(`enum ${type.name} {\n${(type.enumValues || []).map(v => `  ${v.name}`).join('\n')}\n}`);
    ts.push(`export type ${type.name} = ${(type.enumValues || []).map(v => `'${v.name}'`).join(' | ') || 'string'};`, '');
  }
  if (type.kind === 'OBJECT' || type.kind === 'INTERFACE') {
    const keyword = type.kind === 'INTERFACE' ? 'interface' : 'type';
    const fields = type.fields || [];
    sdl.push(`${keyword} ${type.name} {\n${fields.map(field => `  ${field.name}: ${unwrap(field.type).sdl}`).join('\n')}\n}`);
    ts.push(`export interface ${type.name} {`);
    for (const field of fields) {
      const meta = unwrap(field.type);
      const optional = meta.required ? '' : '?';
      const nullable = meta.required ? '' : ' | null';
      ts.push(`  ${field.name}${optional}: ${meta.ts}${nullable};`);
    }
    ts.push('}', '');
  }
  if (type.kind === 'INPUT_OBJECT') {
    const fields = type.inputFields || [];
    sdl.push(`input ${type.name} {\n${fields.map(field => `  ${field.name}: ${unwrap(field.type).sdl}`).join('\n')}\n}`);
    ts.push(`export interface ${type.name} {`);
    for (const field of fields) {
      const meta = unwrap(field.type);
      const optional = meta.required ? '' : '?';
      const nullable = meta.required ? '' : ' | null';
      ts.push(`  ${field.name}${optional}: ${meta.ts}${nullable};`);
    }
    ts.push('}', '');
  }
  if (type.kind === 'UNION') {
    const possible = (type.possibleTypes || []).map(t => t.name).filter(Boolean);
    sdl.push(`union ${type.name} = ${possible.join(' | ')}`);
    ts.push(`export type ${type.name} = ${possible.join(' | ') || 'never'};`, '');
  }
}

fs.writeFileSync(sdlFile, sdl.join('\n\n') + '\n');
fs.writeFileSync(typesFile, ts.join('\n'));
console.log(`Generated ${sdlFile} and ${typesFile}`);
NODE
}

sync_cmd() {
  local endpoint="${1:-}"
  [[ -n "$endpoint" ]] || {
    echo -e "${RED}✖ Endpoint is required.${NC}"
    exit 1
  }
  header
  persist_endpoint "$endpoint"
  if [[ -f codegen.yml || -f codegen.yaml || -f codegen.ts || -f codegen.js || -f graphql.config.js || -f graphql.config.ts ]]; then
    echo -e "${DIM}Detected GraphQL codegen config. Running npx graphql-codegen...${NC}"
    npx graphql-codegen
    exit 0
  fi
  fetch_schema "$endpoint" "$SCHEMA_JSON" >/dev/null
  generate_from_introspection
  echo -e "${GREEN}✅ GraphQL schema synced.${NC}"
}

watch_cmd() {
  local endpoint="${1:-}"
  [[ -n "$endpoint" ]] || endpoint="$(read_endpoint)"
  [[ -n "$endpoint" ]] || {
    echo -e "${RED}✖ Endpoint is required for watch.${NC}"
    exit 1
  }
  header
  echo -e "${DIM}Watching ${endpoint} every 30 seconds. Press Ctrl+C to stop.${NC}"
  while true; do
    bash "$0" sync "$endpoint"
    sleep 30
  done
}

diff_cmd() {
  local endpoint
  endpoint="$(read_endpoint)"
  [[ -n "$endpoint" ]] || {
    echo -e "${RED}✖ No saved endpoint. Run sync first.${NC}"
    exit 1
  }
  header
  fetch_schema "$endpoint" "$CACHE_REMOTE" >/dev/null
  python3 - <<'PY' "$SCHEMA_GRAPHQL" "$CACHE_REMOTE"
from pathlib import Path
import json, re, sys

local_file = Path(sys.argv[1])
remote_file = Path(sys.argv[2])
local_types = set()
if local_file.exists():
    for line in local_file.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^(type|interface|input|enum|union|scalar)\s+([A-Za-z0-9_]+)", line)
        if match:
            local_types.add(match.group(2))

remote = json.loads(remote_file.read_text(encoding="utf-8"))["data"]["__schema"]["types"]
remote_types = {item["name"] for item in remote if item.get("name") and not item["name"].startswith("__")}
added = sorted(remote_types - local_types)
removed = sorted(local_types - remote_types)
print("Added types:")
print("\n".join(f"  + {name}" for name in added) or "  none")
print("\nRemoved types:")
print("\n".join(f"  - {name}" for name in removed) or "  none")
PY
}

clean_cmd() {
  header
  rm -f "$SCHEMA_JSON" "$SCHEMA_GRAPHQL" "$TYPES_FILE" "$CACHE_REMOTE" "$ENDPOINT_FILE"
  echo -e "${GREEN}✅ Removed generated GraphQL files.${NC}"
}

help_text() {
  header
  cat <<EOF
Usage:
  bash scripts/graphql-sync.sh sync <endpoint>
  bash scripts/graphql-sync.sh watch <endpoint>
  bash scripts/graphql-sync.sh diff
  bash scripts/graphql-sync.sh clean
  bash scripts/graphql-sync.sh help
EOF
}

case "$ACTION" in
  sync) sync_cmd "${1:-}" ;;
  watch) watch_cmd "${1:-}" ;;
  diff) diff_cmd ;;
  clean) clean_cmd ;;
  help|--help|-h) help_text ;;
  *) help_text; exit 1 ;;
esac
