#!/usr/bin/env bash
set -euo pipefail
GHOSTFORGE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GREEN='\033[0;32m'; BLUE='\033[0;34m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BOLD='\033[1m'; DIM='\033[2m'; NC='\033[0m'

SPEC_URL="${1:-}"
OUT_DIR="${2:-src/mocks}"
CACHE_DIR="$GHOSTFORGE_DIR/.cache/mock-api"
SPEC_FILE="$CACHE_DIR/openapi-$$.json"

cleanup() { rm -f "$SPEC_FILE"; }
trap cleanup EXIT

echo ""
echo -e "${BLUE}${BOLD}  ╔═══════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}${BOLD}  ║   /mock — OpenAPI → MSW Handlers Generator        ║${NC}"
echo -e "${BLUE}${BOLD}  ╚═══════════════════════════════════════════════════╝${NC}"
echo ""

if [[ -z "$SPEC_URL" ]]; then
  echo -e "  ${DIM}Enter your OpenAPI/Swagger spec URL or local file path:${NC}"
  read -rp "  > " SPEC_URL
fi
[[ -z "$SPEC_URL" ]] && { echo -e "  ${RED}✖  No spec provided.${NC}"; exit 1; }

mkdir -p "$OUT_DIR" "$CACHE_DIR"

echo -e "  ${BLUE}Spec:${NC} $SPEC_URL"
echo -e "  ${BLUE}Output dir:${NC} $OUT_DIR"
echo ""

if [[ "$SPEC_URL" =~ ^https?:// ]]; then
  echo -e "  ${DIM}Fetching OpenAPI spec...${NC}"
  curl -sL "$SPEC_URL" -o "$SPEC_FILE" || { echo -e "  ${RED}✖  Failed to fetch spec.${NC}"; exit 1; }
else
  cp "$SPEC_URL" "$SPEC_FILE"
fi

echo -e "  ${DIM}Generating MSW handlers...${NC}"
echo ""

node -e "
const fs = require('fs');
const spec = JSON.parse(fs.readFileSync('$SPEC_FILE', 'utf8'));
const paths = spec.paths || {};
const handlers = [];
const imports = [];
imports.push(\"import { http, HttpResponse } from 'msw';\");
imports.push('');
imports.push('// Auto-generated by GhostForge /mock');
imports.push('// Regenerate: bash scripts/mock-api.sh $SPEC_URL');
imports.push('');

const baseUrl = (spec.servers && spec.servers[0] && spec.servers[0].url) || '';

for (const [path, methods] of Object.entries(paths)) {
  for (const [method, op] of Object.entries(methods)) {
    if (['get', 'post', 'put', 'patch', 'delete'].includes(method)) {
      const opId = op.operationId || (method + '_' + path.replace(/[^a-zA-Z0-9]/g, '_'));
      const response = op.responses?.['200'] || op.responses?.['201'] || op.responses?.['default'] || {};
      const schema = response?.content?.['application/json']?.schema;

      let mockData = '{}';
      if (schema) {
        if (schema.type === 'array' || schema.items) mockData = '[]';
        else if (schema.properties) {
          const props = {};
          for (const [k, v] of Object.entries(schema.properties || {})) {
            if (v.type === 'string') props[k] = 'string';
            else if (v.type === 'number' || v.type === 'integer') props[k] = 0;
            else if (v.type === 'boolean') props[k] = false;
            else if (v.type === 'array') props[k] = [];
            else props[k] = null;
          }
          mockData = JSON.stringify(props, null, 2);
        }
      }

      const mswMethod = method === 'delete' ? 'http.delete' : \`http.\${method}\`;
      handlers.push(\`  // \${op.summary || opId}\`);
      handlers.push(\`  \${mswMethod}('\\\${baseUrl}\${path}', () => {\`);
      handlers.push(\`    return HttpResponse.json(\${mockData});\`);
      handlers.push('  }),');
      handlers.push('');
    }
  }
}

const handlersFile = [
  ...imports,
  'export const handlers = [',
  ...handlers,
  '];',
  ''
].join('\\n');

const browserFile = \`import { setupWorker } from 'msw/browser';
import { handlers } from './handlers';
export const worker = setupWorker(...handlers);
\`;

const serverFile = \`import { setupServer } from 'msw/node';
import { handlers } from './handlers';
export const server = setupServer(...handlers);
\`;

fs.writeFileSync('$OUT_DIR/handlers.ts', handlersFile);
fs.writeFileSync('$OUT_DIR/browser.ts', browserFile);
fs.writeFileSync('$OUT_DIR/server.ts', serverFile);

const count = handlers.filter(line => line.includes('http.')).length;
console.log('  Generated handlers: ' + count);
console.log('  Files: $OUT_DIR/handlers.ts, browser.ts, server.ts');
" 2>/dev/null && {
  echo -e "  ${GREEN}✅ MSW handlers generated in $OUT_DIR/${NC}"
  echo -e "  ${DIM}  Install MSW: npm install msw --save-dev${NC}"
  echo -e "  ${DIM}  Init worker: npx msw init public/${NC}"
} || {
  echo -e "  ${RED}✖  Generation failed. Check spec format.${NC}"
}

echo ""
