const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const page = fs.readFileSync(path.join(__dirname, '..', 'app', 'agents', 'page.tsx'), 'utf8')
const navbar = fs.readFileSync(path.join(__dirname, '..', 'components', 'Navbar.tsx'), 'utf8')

test('agents page uses the documented snapshot fields and endpoint', () => {
  for (const field of ['health', 'running', 'agents', 'tasks', 'messages', 'phase', 'provider', 'state', 'model', 'task']) {
    assert.match(page, new RegExp(`\\b${field}\\b`), `missing snapshot field ${field}`)
  }
  assert.match(page, /fetch\(['"]\/api\/agents['"]/)
  assert.match(page, /action: 'start'/)
  assert.match(page, /action: 'stop'/)
  assert.match(page, /action: 'say'/)
  assert.match(page, /action: 'add'/)
})

test('agents page and navbar expose all team controls without physical RTL utilities', () => {
  assert.match(navbar, /href: ['"]\/agents['"]/)
  assert.match(page, /Start team/)
  assert.match(page, /Stop team/)
  assert.match(page, /Refresh/)
  assert.match(page, />Say</)
  assert.match(page, />Add</)
  assert.match(page, /id="agent-message"/)
  assert.match(page, /id="agent-task"/)
  assert.match(page, /aria-label="Message recipient"/)
  assert.match(page, /aria-label="Task kind"/)
  assert.doesNotMatch(page, /\b(?:ml|mr|pl|pr)-\d|\btext-(?:left|right)\b/)
})

test('agents page keeps provider values, rendered messages, and refresh/error feedback aligned to the API contract', () => {
  assert.match(page, /agent\.provider \|\| '—'/)
  assert.match(page, /agent\.model \|\| '—'/)
  assert.match(page, /agent\.task \|\| 'Idle'/)
  assert.match(page, /Provider/)
  assert.match(page, /Model/)
  assert.match(page, /Task/)
  assert.match(page, /normalizeMessages\(snapshot\?\.messages\)/)
  assert.match(page, /teamMessage\.text/)
  assert.match(page, /dateTime=\{teamMessage\.datetime\}/)
  assert.match(page, /Unknown sender/)
  assert.match(page, /Unknown recipient/)
  assert.match(page, /No team messages yet\./)
  assert.match(page, /role=\{notice\.error \? 'alert' : 'status'\}/)
  assert.match(page, /onClick=\{\(\) => void load\(\)\}/)
  assert.match(page, /Agent-team command completed\./)
  assert.match(page, /Unable to load agent team\./)
  assert.match(page, /Enter a message before sending\./)
  assert.match(page, /Enter a task title before adding it\./)
})
